[package]
name = "models"
version = "0.1.0"
authors = ["Tom Kirchner <tjk@amazon.com>"]
license = "Apache-2.0 OR MIT"
edition = "2018"
publish = false
build = "build.rs"
# Don't rebuild crate just because of changes to README.
exclude = ["README.md"]

[dependencies]
base64 = "0.13"
bottlerocket-release = { path = "../bottlerocket-release" }
lazy_static = "1.2"
model-derive = { path = "model-derive" }
regex = "1.1"
semver = "0.11.0"
serde = { version = "1.0", features = ["derive"] }
serde_plain = "0.3.0"
snafu = "0.6"
toml = "0.5"
url = "2.1"

[build-dependencies]
cargo-readme = "3.1"
rand = "0.8"

[lib]
# We're picking the current *model* with build.rs, so users shouldn't think
# about importing *models* (plural), just the one current model.
name = "model"
path = "src/lib.rs"
