[package]
name = "static-pods"
version = "0.1.0"
authors = ["Erikson Tung <etung@amazon.com>"]
license = "Apache-2.0 OR MIT"
edition = "2018"
publish = false
build = "build.rs"
# Don't rebuild crate just because of changes to README.
exclude = ["README.md"]

[dependencies]
base64 = "0.13"
log = "0.4"
models = { path = "../../models" }
schnauzer = { path = "../schnauzer" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
simplelog = "0.9"
snafu = "0.6"
tokio = { version = "0.2", default-features = false, features = ["macros", "rt-threaded"] }
# When we update hyper to 0.14+ which has tokio 1:
#tokio = { version = "1", default-features = false, features = ["macros", "rt-multi-thread", "time"] }

[build-dependencies]
cargo-readme = "3.1"
