[package]
name = "libcap"
version = "0.1.0"
edition = "2018"
publish = false
build = "build.rs"

[lib]
path = "pkg.rs"

[[package.metadata.build-package.external-files]]
url = "https://git.kernel.org/pub/scm/libs/libcap/libcap.git/snapshot/libcap-2.44.tar.gz"
sha512 = "d6a31dacd357a7c8fe553e4c004e8084c9025a72073073c92d0281e297172a0cab9174cb318f495eb51804cffcca376d8b7a650f6ba3d4fb31e207fcbc99116f"

[build-dependencies]
glibc = { path = "../glibc" }
libattr = { path = "../libattr" }
