[package]
name = "ecs-agent"
version = "0.1.0"
edition = "2018"
publish = false
build = "build.rs"

[lib]
path = "pkg.rs"

# ECS agent
[[package.metadata.build-package.external-files]]
url = "https://github.com/aws/amazon-ecs-agent/archive/v1.50.2/amazon-ecs-agent-v1.50.2.tar.gz"
sha512 = "5bc946a529c2678b0cd45c3be556b116c26f6d3a3fe3f1cd598cf4fc09eaa8de1ed514bbf62b78892339980b647be49b5152508219181fe567b01152d230db31"

# TODO: Package the CNI plugins
# The ECS agent repository includes two CNI plugins as git submodules.  git
# archive does not include submodules, so the tarball above does not include
# the source of those plugins.

[build-dependencies]
glibc = { path = "../glibc" }
