[package]
name = "docker-cli"
version = "0.1.0"
edition = "2018"
publish = false
build = "build.rs"

[lib]
path = "pkg.rs"

[[package.metadata.build-package.external-files]]
url = "https://github.com/docker/cli/archive/v19.03.13/cli-19.03.13.tar.gz"
sha512 = "738745548bcb416ccadefe1c340b3206b36efb3c222c310b853146f9fe0839bd879576d895bcc53f1f709850ef77888a9990742dd647b9f3cccaa05876a7c9d1"

[build-dependencies]
glibc = { path = "../glibc" }
