[package]
# "." is not allowed in crate names, but we want a friendlier name for the
# directory and spec file, so we override it below.
name = "kubernetes-1_17"
version = "0.1.0"
edition = "2018"
publish = false
build = "build.rs"

[package.metadata.build-package]
package-name = "kubernetes-1.17"

[lib]
path = "pkg.rs"

[[package.metadata.build-package.external-files]]
url = "https://github.com/kubernetes/kubernetes/archive/v1.17.17/kubernetes-1.17.17.tar.gz"
sha512 = "032b033a93416dd8d78672f62718990d129dd47575f79635be6f817d1a8f8d161faf46698627cabfffcd14261afaa8b773537ba5c85ebed4b78906fcad0d07d0"

# This is a large patch, so we don't want to check it into the repo.  It's like
# https://github.com/kubernetes/kubernetes/commit/a94346bef9806a135ebcfda03672966c336c1c17
# but applies to 1.17.x without further context changes.
[[package.metadata.build-package.external-files]]
path = "aws-sdk-go-1.28.2_k8s-1.17.8.patch.bz2"
url = "file:///aws-sdk-go-1.28.2_k8s-1.17.8.patch.bz2"
sha512 = "bb98ec01b9e0aa843b8a33bf753277ff323f88061a00bc18404a488231fc6cc39208ad43b9c39338bb0a4f1e1b2751d6a2e71f86240d8694bf711a6a531f74d1"

[build-dependencies]
glibc = { path = "../glibc" }
