[package]
name = "iputils"
version = "0.1.0"
edition = "2018"
publish = false
build = "build.rs"

[lib]
path = "pkg.rs"

[[package.metadata.build-package.external-files]]
path = "iputils-s20200821.tar.gz"
url = "https://github.com/iputils/iputils/archive/s20200821.tar.gz"
sha512 = "4a57c3637cdd9aab2600682774e27370716cbdf1c7ac8ae61bf86c21c08701a5b697792df4aa95309b196eaa74f3cb6b2836a40f04da0e602156e982ac99d8c9"

[build-dependencies]
glibc = { path = "../glibc" }
libcap = { path = "../libcap" }
