[package]
name = "iputils"
version = "0.1.0"
edition = "2018"
publish = false
build = "build.rs"

[lib]
path = "pkg.rs"

[[package.metadata.build-package.external-files]]
path = "iputils-20210202.tar.gz"
url = "https://github.com/iputils/iputils/archive/20210202.tar.gz"
sha512 = "af600fe74e1b78c0da66c378f55eb468d62206aaae1864693f7ec79833c9c0de95843573d1792627695f08ecfcdb4e79c354065daf178d393fcc6ef9a8a5d526"

[build-dependencies]
glibc = { path = "../glibc" }
libcap = { path = "../libcap" }
