[package]
name = "wicked"
version = "0.1.0"
edition = "2018"
publish = false
build = "build.rs"

[lib]
path = "pkg.rs"

[[package.metadata.build-package.external-files]]
url = "https://github.com/openSUSE/wicked/archive/version-0.6.64.tar.gz"
sha512 = "5f0ef9831cba74b06f660a086c92e7c93c756fce9e402fc011bc14f2e29cb5be2ae1793844b7a1e89f3d423e10cdbe579f7fc73a02ad62cbe5ed49a0eef4b648"

[build-dependencies]
glibc = { path = "../glibc" }
libdbus = { path = "../libdbus" }
libiw = { path = "../libiw" }
libnl = { path = "../libnl" }
systemd = { path = "../systemd" }
