[package]
name = "tcpdump"
version = "0.1.0"
edition = "2018"
publish = false
build = "build.rs"

[lib]
path = "pkg.rs"

[[package.metadata.build-package.external-files]]
url = "http://www.tcpdump.org/release/tcpdump-4.99.0.tar.gz"
sha512 = "03a434ec41c0026f237bc1e7a928b7ce67dbc342a8d982caded93d987bd356faf706a9d884231bd94f5e2a8580499fe95a28728e37a6672e371a1501ec5d6f79"

[build-dependencies]
glibc = { path = "../glibc" }
libpcap = { path = "../libpcap" }
