[package]
name = "libnftnl"
version = "0.1.0"
edition = "2018"
publish = false
build = "build.rs"

[lib]
path = "pkg.rs"

[[package.metadata.build-package.external-files]]
url = "http://netfilter.org/projects/libnftnl/files/libnftnl-1.1.9.tar.bz2"
sha512 = "8e2551a902a320769198e0ebce52596501c548e230c3172ba4989e25dcb3dd6c9b97a104af69b93ede4ef298811cff10608758e6f1d274e758d87306c4b50f25"

[build-dependencies]
glibc = { path = "../glibc" }
libmnl = { path = "../libmnl" }
